FROM golang:alpine as builder
WORKDIR $GOPATH/src/go.k6.io/k6

RUN apk --no-cache add git
RUN go install go.k6.io/xk6/cmd/xk6@latest
RUN xk6 build \
    --with github.com/grafana/xk6-sql \
    --with github.com/grafana/xk6-sql-driver-mysql \
    --output /k6

FROM alpine:3.18
RUN apk add --no-cache ca-certificates
COPY --from=builder /k6 /usr/bin/k6

ENTRYPOINT ["k6"]
